# Generated by Django 2.1 on 2018-09-07 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=200)),
                ('starting_date', models.DateField(default=django.utils.timezone.now)),
                ('ending_date', models.DateField(default=django.utils.timezone.now)),
                ('work_status', models.CharField(max_length=200)),
            ],
        ),
    ]
